# Generated by Django 4.2.2 on 2023-06-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
