# Generated by Django 4.2.2 on 2023-06-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctapp', '0002_alter_product_mobile_alter_product_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
