# Generated by Django 4.2.2 on 2023-06-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctapp', '0003_alter_product_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='pname',
        ),
    ]
